// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/webApi/webApi.proto

package go_micro_api_webApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for WebApi service

func NewWebApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for WebApi service

type WebApiService interface {
	AddLottery(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetLotteryList(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetInfoByUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetListByUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Login(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Register(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type webApiService struct {
	c    client.Client
	name string
}

func NewWebApiService(name string, c client.Client) WebApiService {
	return &webApiService{
		c:    c,
		name: name,
	}
}

func (c *webApiService) AddLottery(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.AddLottery", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webApiService) GetLotteryList(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.GetLotteryList", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webApiService) GetInfoByUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.GetInfoByUserId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webApiService) GetListByUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.GetListByUserId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webApiService) Login(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webApiService) Register(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WebApi.Register", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WebApi service

type WebApiHandler interface {
	AddLottery(context.Context, *Request, *Response) error
	GetLotteryList(context.Context, *Request, *Response) error
	GetInfoByUserId(context.Context, *Request, *Response) error
	GetListByUserId(context.Context, *Request, *Response) error
	Login(context.Context, *Request, *Response) error
	Register(context.Context, *Request, *Response) error
}

func RegisterWebApiHandler(s server.Server, hdlr WebApiHandler, opts ...server.HandlerOption) error {
	type webApi interface {
		AddLottery(ctx context.Context, in *Request, out *Response) error
		GetLotteryList(ctx context.Context, in *Request, out *Response) error
		GetInfoByUserId(ctx context.Context, in *Request, out *Response) error
		GetListByUserId(ctx context.Context, in *Request, out *Response) error
		Login(ctx context.Context, in *Request, out *Response) error
		Register(ctx context.Context, in *Request, out *Response) error
	}
	type WebApi struct {
		webApi
	}
	h := &webApiHandler{hdlr}
	return s.Handle(s.NewHandler(&WebApi{h}, opts...))
}

type webApiHandler struct {
	WebApiHandler
}

func (h *webApiHandler) AddLottery(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.AddLottery(ctx, in, out)
}

func (h *webApiHandler) GetLotteryList(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.GetLotteryList(ctx, in, out)
}

func (h *webApiHandler) GetInfoByUserId(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.GetInfoByUserId(ctx, in, out)
}

func (h *webApiHandler) GetListByUserId(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.GetListByUserId(ctx, in, out)
}

func (h *webApiHandler) Login(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.Login(ctx, in, out)
}

func (h *webApiHandler) Register(ctx context.Context, in *Request, out *Response) error {
	return h.WebApiHandler.Register(ctx, in, out)
}
